Repository lkriffell/adopt_dont_shop, pull requests merged in 2020-09, with the labels that each got.

#7 Applications
  app/models/shelter.rb
  app/views/shelters/show.html.erb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/features/shelters/show_spec.rb
  spec/models/shelters_spec.rb
Labels: Author resolves comments, Author think ready to merge, Peer coded together, Reviewer merges, Reviewer thinks ready to merge

#8 Complete through user story 33
  app/controllers/pets_controller.rb
  app/views/pets/edit.html.erb
  app/views/pets/index.html.erb
  app/views/pets/new.html.erb
  app/views/pets/show.html.erb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  paired-README.md
  spec/features/pets/edit_spec.rb
  spec/features/pets/index_spec.rb
  spec/features/pets/new_spec.rb
  spec/features/pets/show_spec.rb
Labels: Author resolves comments, Peer coded together, Reviewer adds line comments, Reviewer merges

#10 Applications refactor
  app/views/applications/show.html.erb
  app/views/pets/show.html.erb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  paired-README.md
  spec/features/applications/apply_spec.rb
  spec/features/applications/show_spec.rb
Labels: Author think ready to merge, Reviewer adds line comments, Reviewer merges

#9 moved shelter params to private
  app/controllers/shelters_controller.rb
  app/views/shelters/edit.html.erb
  app/views/shelters/new.html.erb
  coverage/.resultset.json
  coverage/index.html
  spec/features/shelters/edit_spec.rb
  spec/features/shelters/new_spec.rb
Labels: Author resolves comments, Reviewer merges, Reviewer thinks ready to merge

#11 General Refactor
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/controllers/applications_controller.rb
  app/controllers/applications_pets_controller.rb
  app/controllers/pets_controller.rb
  app/controllers/shelters_controller.rb
  app/models/pet.rb
  app/views/applications/show.html.erb
  app/views/layouts/application.html.erb
  app/views/pets/_form.html.erb
  app/views/pets/edit.html.erb
  app/views/pets/index.html.erb
  app/views/pets/new.html.erb
  app/views/pets/show.html.erb
  app/views/shelters/edit.html.erb
  app/views/shelters/new.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20200825225311_add_favorite_column_to_pet_table.rb
  paired-README.md
  spec/features/applications/apply_spec.rb
  spec/features/applications/show_spec.rb
  spec/features/pets/edit_spec.rb
  spec/features/pets/index_spec.rb
  spec/features/pets/new_spec.rb
  spec/features/pets/show_spec.rb
  spec/features/shelters/edit_spec.rb
  spec/features/shelters/new_spec.rb
Labels: Author resolves comments, Author think ready to merge, Reviewer adds line comments, Reviewer merges, Reviewer thinks ready to merge
