Repository lkriffell/adopt_dont_shop, pull requests merged in 2020-08, with the labels that each got.

#1 Complete Shelter Review Page (User Stories 5 & 6)
  app/controllers/reviews_controller.rb
  app/views/reviews/edit.html.erb
  app/views/shelters/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/features/reviews/show_spec.rb
Labels: Peer coded together, Reviewer merges

#2 user story 7 done
  app/controllers/reviews_controller.rb
  app/views/shelters/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/features/reviews/show_spec.rb
Labels: Author resolves comments, Author think ready to merge, Peer coded together, enhancement

#3 Pet favorites: Add, show, Delete
  app/assets/stylesheets/application.css
  app/controllers/pets_controller.rb
  app/models/pet.rb
  app/views/layouts/application.html.erb
  app/views/pets/show.html.erb
  app/views/pets/show_favorite.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20200825225311_add_favorite_column_to_pet_table.rb
  db/schema.rb
  db/seeds.rb
  paired-README.md
  spec/features/layouts/application_spec.rb
  spec/features/pets/show_spec.rb
  spec/models/pets_spec.rb
  spec/models/shelters_spec.rb
Labels: Reviewer merges

#4 Favorites
  app/controllers/pets_controller.rb
  app/views/pets/show_favorite.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/features/pets/show_spec.rb
Labels: Author resolves comments, Author think ready to merge, Peer coded together, Reviewer adds line comments, Reviewer thinks ready to merge

#5 Applications
  app/assets/stylesheets/application.css
  app/controllers/applications_controller.rb
  app/controllers/applications_pets_controller.rb
  app/controllers/pets_controller.rb
  app/models/application.rb
  app/models/applications_pets.rb
  app/models/pet.rb
  app/views/applications/apply.html.erb
  app/views/applications/show.html.erb
  app/views/layouts/application.html.erb
  app/views/pets/show.html.erb
  app/views/pets/show_favorite.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20200827210950_edit_structure.rb
  db/migrate/20200827211418_create_applications.rb
  db/migrate/20200827211556_create_applications_pets.rb
  db/schema.rb
  db/seeds.rb
  paired-README.md
  spec/features/applications/apply_spec.rb
  spec/features/applications/show_spec.rb
  spec/features/pets/show_spec.rb
  spec/models/application_spec.rb
Labels: Author resolves comments, Author think ready to merge, Peer coded together, Reviewer merges
